[package]
name = "rustizado"
version = "0.1.0"
edition = "2024"

[dependencies]
uiautomation = "0.17.2"

[dependencies.windows]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_NetworkManagement_WiFi"

]

